### ISSUE TITLE
run nightly

### ISSUE THREAD

**Issue by adriaanm** [scala/compiler-benchmark#40] opened 2017-08-31 15:50 UTC
I hope I haven't missed the existing ticket somewhere else. JB would really like this to happen soon.

**Comment by lrytz** [comment] 2017-09-05 10:00
i guess he means to run the "scala" benchmark nightly, since we run the others mergely. i'll take a look.

**Comment by adriaanm** [comment] 2017-09-05 17:00
Thanks

**Comment by lrytz** [comment] 2017-09-06 11:01
https://scala-ci.typesafe.com/benchq/benchmarks - benchmarks can now be made run at most every n days

i'll monitor things to see if everything works as intended.

**Comment by lrytz** [comment] 2017-09-06 14:32
I merged some PRs, seems to work as expected so far.

**Closed** 2017-09-08 06:13 UTC
